FROM python:3.8-slim

RUN apt-get update && apt-get install -y chromium

COPY /scrapper_superalimentos/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY /scrapper_superalimentos/scrapper_superalimentos.py /app/scrapper_superalimentos.py
CMD ["python", "/app/scrapper_superalimentos.py"]