FROM python:3.8-slim

RUN apt-get update && apt-get install -y chromium

COPY /scrapper_iterativo/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt
RUN pip install selenium


COPY /scrapper_iterativo/scrapper_iterativo.py /app/scrapper_iterativo.py
CMD ["python", "/app/scrapper_iterativo.py"]