FROM python:3.8-slim

RUN apt-get update && apt-get install -y libpq-dev

COPY /pandas_transform/requirements.txt /app/requirements.txt
RUN pip install -r /app/requirements.txt

COPY /pandas_transform/pandas_transform.py /app/pandas_transform.py
CMD ["python", "/app/pandas_transform.py"]