FROM python:3.8-slim

RUN apt-get update && apt-get install unzip && apt-get install -y libpq-dev && apt-get install -y wget 
RUN apt-get update && \
    apt-get -y install gcc mono-mcs && \   
    apt-get install -y chromium 

COPY requirements.txt ./   
RUN pip install selenium
RUN pip install --no-cache-dir -r requirements.txt

COPY scrapperConsumo.py /app/scrapperConsumo.py
COPY subirData.py /app/subirData.py

CMD ["python", "/app/scrapperConsumo.py"]